module.exports = {
	customProperties: {
		'--borderRadius': '4px',
		'--brandDarkGreyColor': '#313b3f',
		'--brandDarkWhiteColor': '#f8f9fb',
		'--brandGreenColor': '#0aafbe',
		'--brandGreyColor': '#616f77',
		'--brandLightBlackColor': '#23232c',
		'--brandLightGreyColor': '#d7dde0',
		'--brandMidGreyColor': '#495156',
		'--brandPaleGreyColor': '#e9eff1',
		'--brandRedColor': '#ff160a',
		'--brandYellowColor': '#ffb00a',
		'--collapsedNavWidth': '0',
		'--collapsedSidebarWidth': '57px',
		'--dangerHover': '#f31e00',
		'--expandedNavWidth': '279px',
		'--expandedSidebarWidth': '227px',
		'--fontBold': '600',
		'--fontNormal': '400',
		'--fontSemiBold': '500',
		'--gridGap': '15px',
		'--horizontalSidebarHeight': '64px',
		'--inputHeight': '38px',
		'--linkColor': '#616f77',
		'--sidebarLinkColor': '#909da5',
		'--sidebarAnimationDuration': '200ms',
		'--treemapBlueHigh': '#016b74',
		'--treemapBlueLow': '#89d7de',
		'--zIndexHigh': '300',
		'--zIndexLow': '100',
		'--zIndexMax': '9999',
		'--zIndexMed': '200'
	}
};
